services:
  db:
    image: postgres:13
    container_name: pg_container
    environment:
      POSTGRES_USER: database_3qhp_user
      POSTGRES_PASSWORD: XDlQhcomymh3Ppq0Mpmx0ShfG1rVg9CF
      POSTGRES_DB: database_3qhp
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
