version: '3.8'

services:
  web:
    build: ./app
    container_name: php_app
    ports:
      - "80:80"
    environment:
      DB_HOST: dpg-d0cfcj6uk2gs738mamd0-a
      DB_PORT: 5432
      DB_NAME: database_3qhp
      DB_USER: database_3qhp_user
      DB_PASSWORD: XDlQhcomymh3Ppq0Mpmx0ShfG1rVg9CF
